server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bxb_text?useUncode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#  multipart上传限制的配置 config里面也要弄
  http:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

